'''title'''
__title__ = 'sciogovterminal'
'''description'''
__description__ = '''Sciogovterminal: Browse "The State Council Information Office of the People's Republic of China" in the terminal.'''
'''url'''
__url__ = 'https://github.com/CharlesPikachu/sciogovterminal'
'''version'''
__version__ = '0.1.0'
'''author'''
__author__ = 'Zhenchao Jin'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2022 Zhenchao Jin'